import = ["/Users/pjl/.config/alacritty/colors/_default.toml"]

[font]
normal      = { family = "JetbrainsMono Nerd Font", style ="Light" }
bold        = { family = "JetbrainsMono Nerd Font", style ="Bold" }
italic      = { family = "JetbrainsMono Nerd Font", style ="Light Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style ="Bold Italic" }
size        = 15

[env]
TERM="xterm-256color"

