import = ["/Users/pjl/.theme.toml"]

[window]
dimensions = { columns = 120, lines = 40 }
decorations = "Buttonless"
option_as_alt = "OnlyLeft"
padding = { y = 1, x = 1 }
dynamic_padding = true

[font]
normal      = { family = "JetbrainsMono Nerd Font", style ="Regular"        }
bold        = { family = "JetbrainsMono Nerd Font", style ="Medium"            }
italic      = { family = "JetbrainsMono Nerd Font", style ="Regular" }
bold_italic = { family = "JetbrainsMono Nerd Font", style ="Medium Italic"     }
size        = 16

[mouse]
hide_when_typing = true

[env]
TERM="xterm-256color"

