import = ["/Users/pjl/.theme.toml"]

# [font]
# normal      = { family = "SFMono Nerd Font", style ="Light" }
# bold        = { family = "SFMono Nerd Font", style ="Medium" }
# italic      = { family = "SFMono Nerd Font", style ="Light Italic" }
# bold_italic = { family = "SFMono Nerd Font", style ="Medium Italic" }
# size        = 15

[font]
normal      = { family = "JetbrainsMono Nerd Font", style ="ExtraLight" }
bold        = { family = "JetbrainsMono Nerd Font", style ="Medium" }
italic      = { family = "JetbrainsMono Nerd Font", style ="ExtraLight Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style ="Medium Italic" }
size        = 17

[env]
TERM="xterm-256color"

