import = ["/Users/pjl/.theme.toml"]

[window]
decorations = "None"

[window.padding] 
y = 2
x = 2

[font]
normal      = { family = "JetbrainsMono Nerd Font", style ="ExtraLight" }
bold        = { family = "JetbrainsMono Nerd Font", style ="Medium" }
italic      = { family = "JetbrainsMono Nerd Font", style ="ExtraLight Italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style ="Medium Italic" }
size        = 16

[env]
TERM="xterm-256color"

