# everforest_light_hard = &everforest_light_hard
[colors.primary]
background = "#FFFBEF"
foreground = "#5C6A72"

[colors.normal]
black = "#5C6A72"
red = "#F85552"
green = "#8DA101"
yellow = "#DFA000"
blue = "#3A94C5"
magenta = "#DF69BA"
cyan = "#35A77C"
white = "#E8E5D5"

[colors.bright]
black = "#5C6A72"
red = "#F85552"
green = "#8DA101"
yellow = "#DFA000"
blue = "#3A94C5"
magenta = "#DF69BA"
cyan = "#35A77C"
white = "#E8E5D5"
